config/routes.rb
Rails.application.routes.draw do
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	get 'logout', to: 'sessions#destroy'
	resources :users

	get 'users/:id/follow', to: 'users#follow'
	get 'users/:id/follower', to: 'users#follower'

	get 'friends/search', to: 'friends#index'
	post 'friends/search', to: 'friends#search'
	post 'friends/follow', to: 'friends#create'
	delete 'friends/follow', to: 'friends#destroy'

	post 'voices', to: 'voices#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :from_user, class_name: User, foreign_key: :from_user_id
	belongs_to :to_user, class_name: User,   foreign_key: :to_user_id

	validates :from_user_id, presence: true
	validates :to_user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :follows_from, class_name: Friend, foreign_key: :from_user_id, dependent: :destroy
	has_many :follows_to,   class_name: Friend, foreign_key: :to_user_id,   dependent: :destroy
	has_many :following, through: :follows_from, source: :to_user
	has_many :followed,  through: :follows_to,   source: :from_user
	has_many :voices, dependent: :destroy
	has_secure_password
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name, presence: true

	# 開発終わったらformat: { with: VALID_EMAIL_REGEX }追加
	validates :email, presence: true, uniqueness: true

	# 開発終わったらlength: { minimum: 8 }追加
  validates :password, presence: true

  validates :search_word, presence: true, uniqueness: true

  # 指定ユーザをフォローしているかどうかを返す
	def following?(user)
		self.following.where(id: user.id).any?
	end

	# 指定ユーザにフォローされているかどうかを返す
	def followed_by?(user)
		self.followed.where(id: user.id).any?
	end
end

app/models/voice.rb
class Voice < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	def index
		@result = ""
	end

	def search
		if params[:search_word] != current_user.search_word
			@search_user = User.find_by(search_word: params[:search_word])
			if @search_user.nil?
				flash[:error] = "no hit..."
			end
		else
			flash[:error] = "That's mine..."
		end
		render "index"
	end

	def create
		to_user_id = params[:to_user_id]
		if current_user.id != to_user_id
			@friend = Friend.create(from_user_id: current_user.id, to_user_id: to_user_id)
		else
			flash[:notice] = "処理エラー"
		end
		redirect_to user_path(to_user_id)
	end

	def destroy
		to_user_id = params[:to_user_id]
		@friend = Friend.find_by(from_user_id: current_user, to_user_id: to_user_id)
		if @friend
			@friend.destroy
		else
			flash[:notice] = "処理エラー"
		end
		redirect_to user_path(to_user_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
    authenticate_service = Auth::UserAuthenticateService.new(params[:email], params[:password])
    if user_id = authenticate_service.authenticate
    	session[:user_id] = user_id
      redirect_to users_path
    else
      flash.now[:danger] = 'emailまたはpasswordが間違っています'
      render "new"
    end
	end

	def destroy
		session[:user_id] = nil
    redirect_to login_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :login_check, only: %i(index edit update destroy)
	before_action :permission_check, only: %i(edit)
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			authenticate_service = Auth::UserAuthenticateService.new(@user.email, @user.password)
	    if user_id = authenticate_service.authenticate
	    	session[:user_id] = user_id
	      redirect_to users_path
	    else
	    	p 'user create faild!!'
	    	redirect_to login_path
	    end
		end
	end

	def index
		@voices = current_user.voices
		@target_user = User.find(current_user.id).following
		if !@target_user.nil?
		@target_user.each do |user|
			@voices += user.voices
			end
		end
		@voices_res = @voices.sort { |aa, bb| bb.created_at <=> aa.created_at }
	end

	def show
		@show_user = User.find(params[:id])
		@voices = @show_user.voices
		@voices_res = @voices.sort { |aa, bb| bb.created_at <=> aa.created_at }
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
    if @user.update(user_params)
        redirect_to @user
    else
        render 'edit'
    end
	end

	def follow
		@user = User.find(params[:id])
		@follows = User.find(params[:id]).following
	end

	def follower
		@user = User.find(params[:id])
		@followers = User.find(params[:id]).followed
	end


	private
	def user_params
		params.require(:user).permit(:name, :email, :search_word, :password, :password_confirmation)
	end

	def login_check
    if session[:user_id].nil?
    	redirect_to login_path
    end
	end

	def permission_check
		if current_user.id != params[:id].to_i
			redirect_to user_path(params[:id]), flash: { denger: '権限がありません。'}
		end
	end
end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  def create
  	if !params[:text].empty?
  		@voice = Voice.create(text: params[:text], user_id: current_user.id)
  	end
		redirect_to users_path
  end

  private
	def login_check
    if session[:user_id].nil?
    	redirect_to login_path
    end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/voices_helper.rb
module VoicesHelper
end

app/views/friends/index.erb
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <title>Friend search</title>
</head>
<body>
  <h1>friend search!!</h1>
  <%= form_tag friends_search_path,
    :method => "post" do %>
    <p>
      <%= label_tag :search_word %>
      <%= text_field_tag :search_word %>
    </p>
    <p><%= submit_tag "Search" %></p>
  <% end %>

  <% if !@search_user.nil? %>
    <h2>hit!!</h2>
    <p><strong>name : </strong><%= link_to @search_user.name, user_path(@search_user.id) %></p>
  <% else %>
    <h2><%= flash[:error] %></h2>
    <% flash[:error] = "" %>
  <% end %>
  <%= link_to 'Back top', users_path %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsFriends</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>User edit page</title>
</head>
<body>
  <h1>User edit page</h1>
  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :search_word %>
    <%= f.text_field :search_word %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </p>

  <p><%= f.submit %></p>
  <% end %>
  <%= link_to "Back user page", user_path(@user) %>

</body>
</html>

app/views/users/follow.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>follow list</title>
</head>
<body>
  <h1>Follow list</h1>
  <ul>      
    <% @follows.each do |user| %>
      <li><strong>name : </strong><%= link_to user.name, user_path(user.id) %></li>
    <% end %>
  </ul>
  <%= link_to "Back user page", user_path(@user) %>
</body>
</html>

app/views/users/follower.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>follower list</title>
</head>
<body>
  <h1>Follower list</h1>
  <ul>      
      <% @followers.each do |user| %>
        <li><strong>name : </strong><%= link_to user.name, user_path(user.id) %></li>
      <% end %>
  </ul>
  <%= link_to "Back user page", user_path(@user) %>
</body>
</html>

app/views/users/index.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>welcome</title>
</head>
<body>
  <h1>welcome!! friend App!!</h1>
  <%= link_to 'Logout', logout_path, data: { confirm: 'また遊びに来てくれますか？' } %>
  <%= link_to 'Show user', user_path(current_user) %>
  <%= link_to 'Search friends!!', friends_search_path %>
  <%= form_tag voices_path,
    :method => "post" do %>
    <p>
      <%= label_tag :text %>
      <%= text_field_tag :text %>
    </p>
    <p><%= submit_tag "speak!!" %></p>
  <% end %>
  <ul>
    <% @voices_res.each do |voice| %>
      <li style="margin-bottom: 10px">
        <strong>speaker : </strong><%= link_to voice.user.name, user_path(voice.user.id) %><br>
        <strong>voice : </strong><%= voice.text %>
      </li>
    <% end %>
  </ul>
</body>
</html>

app/views/users/new.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>Sign in</title>
</head>
<body>
  <h1>Sign in</h1>
  <%= form_for @user do |f| %>
  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited
      this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :search_word %>
    <%= f.text_field :search_word %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.text_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %>
    <%= f.text_field :password_confirmation %>
  </p>

  <p><%= f.submit %></p>
  <% end %>
  <%= link_to "Login", login_path %>

</body>
</html>

app/views/users/show.erb
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <title>User Page</title>
</head>
<body>
  <% if @show_user.id == current_user.id %>
    <h1>My page</h1>
  <% else %>
    <h1>User page</h1>
    <% msg = "" %>
    <% if current_user.followed_by?(User.find(@show_user.id)) %>
      <% msg = "followされているよ!!" %>
      <% if current_user.following?(User.find(@show_user.id)) %>
        <% msg = "nice friend!!" %>
      <% end %>
    <% end %>
    <p><%= msg %></p>
    <% if current_user.following?(User.find(@show_user.id)) %>
      <%= form_tag friends_follow_path,
      :method => "delete" do %>
        <%= hidden_field_tag :to_user_id, @show_user.id %>
        <%= submit_tag "unfollow" %>
      <% end %>
    <% else %>
      <%= form_tag friends_follow_path,
      :method => "post" do %>
        <%= hidden_field_tag :to_user_id, @show_user.id %>
        <%= submit_tag "follow" %>
      <% end %>
    <% end %>
  <% end %>

  <% flash.each do |key, value| %>
    <%= value %>
  <% end %>
  <p>
    <strong>name:</strong>
    <%= @show_user.name %>
  </p>
  <p>
    <strong>email:</strong>
    <%= @show_user.email %>
  </p>
  <p>
    <strong>search_word:</strong>
    <%= @show_user.search_word %>
  </p>

  <%= link_to 'Follow list', :action => 'follow' %>
   | <%= link_to 'Follower list', :action => 'follower' %><br>

  <%= link_to 'Back top', users_path %>
  <% if @show_user.id == current_user.id %>
   | <%= link_to 'Edit', edit_user_path(@show_user) %>
  <% end %>

  <h2>Voice history</h2>
  <ul>
  <% @voices_res.each do |voice| %>
    <li style="margin-bottom: 10px">
      <strong>speaker : </strong><%= link_to voice.user.name, user_path(voice.user.id) %><br>
      <strong>voice : </strong><%= voice.text %>
    </li>
  <% end %>
  </ul>
</body>
</html>